import { prisma } from '@/lib/prisma';


const main = async () => {

    const newCategory = [
        // -- State of Mental Health in the Philippines (topicOrder: 0) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "State of Mental Health in the Philippines", topicOrder: 0, conceptText: "Mental Health Care Delivery System", conceptOrder: 0, allocatedMinutes: 120 },

        // -- Psychobiologic Bases of Behavior (topicOrder: 1) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychobiologic Bases of Behavior", topicOrder: 1, conceptText: "Neuroscience—Neuroanatomy/Physiology", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychobiologic Bases of Behavior", topicOrder: 1, conceptText: "Concepts and Patterns of Human Behavior", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychobiologic Bases of Behavior", topicOrder: 1, conceptText: "Global and Regional Perspectives on Mental Health", conceptOrder: 2, allocatedMinutes: 120 },

        // -- Therapeutic Models and its Relevance to Nursing Practice (topicOrder: 2) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Psychoanalytic Model", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Erik Eriksons's Model of Psychosocial Development", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Harry Stack Sullivan: Interpersonal Theory and Psychotherapy", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Hildegard Peplau's Theory of Interpersonal Relations", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Jean Piaget's Cognitive Development Model", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Aaron Beck's Cognitive Triad of Negative Thoughts", conceptOrder: 5, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Cognitive Therapy", conceptOrder: 6, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Therapeutic Models and its Relevance to Nursing Practice", topicOrder: 2, conceptText: "Stress Models", conceptOrder: 7, allocatedMinutes: 120 },

        // -- Understanding Stress (topicOrder: 3) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Understanding Stress", topicOrder: 3, conceptText: "Acute and Long Term Effects of Stress", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Understanding Stress", topicOrder: 3, conceptText: "General Adaptation Syndrome (GAS)", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Understanding Stress", topicOrder: 3, conceptText: "Measuring Stress and Coping Styles", conceptOrder: 2, allocatedMinutes: 120 },

        // -- Psychopathology: Etiology and Psychodynamics (topicOrder: 4) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Disturbances in Thought/Content Process: Schizophrenia and Other Psychosis", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Anxiety Disorder", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Mood Disorders", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Personality Disorders", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Cognitive Disorders", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Eating Disorders", conceptOrder: 5, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Sexual Disorders", conceptOrder: 6, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Substance Abuse", conceptOrder: 7, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Disorders in Childhood Adolescents", conceptOrder: 8, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS OF MENTAL HEALTH AND ILLNESS", topicHeader: "Psychopathology: Etiology and Psychodynamics", topicOrder: 4, conceptText: "Domestic Violence", conceptOrder: 9, allocatedMinutes: 120 },

        // -- Assessment (topicOrder: 5) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Assessment", topicOrder: 5, conceptText: "Subjective Data", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Assessment", topicOrder: 5, conceptText: "Objective Data", conceptOrder: 1, allocatedMinutes: 120 },

        // -- Nursing Diagnosis (topicOrder: 6) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Nursing Diagnosis", topicOrder: 6, conceptText: "NANDA Taxonomy", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Nursing Diagnosis", topicOrder: 6, conceptText: "Diagnosis DSM IV / V", conceptOrder: 1, allocatedMinutes: 120 },

        // -- Planning and Implementation of Care: Nurse-Client Relationship (topicOrder: 7) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Nurse-Client Relationship", topicOrder: 7, conceptText: "Orientation Stage", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Nurse-Client Relationship", topicOrder: 7, conceptText: "Working Stage", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Nurse-Client Relationship", topicOrder: 7, conceptText: "Termination Stage", conceptOrder: 2, allocatedMinutes: 120 },

        // -- Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP) (topicOrder: 8) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP)", topicOrder: 8, conceptText: "Depressive Disorder", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP)", topicOrder: 8, conceptText: "Post-Traumatic Stress Disorder", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP)", topicOrder: 8, conceptText: "Psychosis", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP)", topicOrder: 8, conceptText: "Epilepsy/Seizures", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP)", topicOrder: 8, conceptText: "Intellectual Disability", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Mental Health Gap Action Programme (mhGAP)", topicOrder: 8, conceptText: "Suicide", conceptOrder: 5, allocatedMinutes: 120 },

        // -- Planning and Implementation of Care: Treatment Modalities (topicOrder: 9) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Electroconvulsive Therapy", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Alternative Complementary Therapy", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Psychotherapies", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Behavioral Therapies", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Cognitive Therapies", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Milieu Therapy / Therapeutic Milieu", conceptOrder: 5, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Art Therapy", conceptOrder: 6, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Dance/Music Therapy", conceptOrder: 7, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Attitude Therapies", conceptOrder: 8, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Antipsychotics", conceptOrder: 9, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Anxiolytics", conceptOrder: 10, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Anti-depressants", conceptOrder: 11, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Lithium or Mood Stabilizers", conceptOrder: 12, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Complementary and Alternative Therapy", conceptOrder: 13, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Planning and Implementation of Care: Treatment Modalities", topicOrder: 9, conceptText: "Nutrition and Diet Therapy", conceptOrder: 14, allocatedMinutes: 120 },

        // -- Evaluation of Care (topicOrder: 10) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "NURSING PROCESS IN PSYCHIATRIC/MENTAL HEALTH CARE", topicHeader: "Evaluation of Care", topicOrder: 10, conceptText: "Outcome Based", conceptOrder: 0, allocatedMinutes: 120 },

        // -- Care of Clients with Altered Ventilatory Functions (topicOrder: 11) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Pulmonary Embolism", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Acute Respiratory Distress Syndrome", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Acute Lung Injury", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Respiratory Failure", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Ventilator-Associated Pneumonia", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Respiratory Pandemics", conceptOrder: 5, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Pulmonary Hypertension", conceptOrder: 6, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Ventilatory Functions", topicOrder: 11, conceptText: "Pneumothorax", conceptOrder: 7, allocatedMinutes: 120 },

        // -- Care of Clients with Altered Tissue Perfusion (topicOrder: 12) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Acute Ischemic Heart Disease", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Heart Failure", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Cardiogenic Shock", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Coronary Arterial Disease", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Hypertensive Crisis", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Cardiomyopathy", conceptOrder: 5, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Tissue Perfusion", topicOrder: 12, conceptText: "Arrhythmias", conceptOrder: 6, allocatedMinutes: 120 },

        // -- Care of Clients with Altered Elimination (topicOrder: 13) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Acute Gastrointestinal Bleeding", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Intra-Abdominal Hypertension", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Abdominal Compartment Syndrome", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Liver Failure", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Acute Pancreatitis", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Diabetic Ketoacidosis", conceptOrder: 5, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Hyperglycemia", conceptOrder: 6, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Hyperosmolar Non-Ketotic Acidosis", conceptOrder: 7, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Elimination", topicOrder: 13, conceptText: "Acute Renal Failure", conceptOrder: 8, allocatedMinutes: 120 },

        // -- Care of Clients with Altered Preception (topicOrder: 14) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Preception", topicOrder: 14, conceptText: "Traumatic Alterations", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Preception", topicOrder: 14, conceptText: "Acute Ischemic Stroke", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Preception", topicOrder: 14, conceptText: "Traumatic Spinal Cord Injury", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Altered Preception", topicOrder: 14, conceptText: "Seizures", conceptOrder: 3, allocatedMinutes: 120 },

        // -- Care of Clients with Multi-System Problem (topicOrder: 15) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Multi-System Problem", topicOrder: 15, conceptText: "Shock", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Multi-System Problem", topicOrder: 15, conceptText: "Systemic Inflammatory Responses Syndrome (SIRS)", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "CONCEPTS ON ACUTE BIOLOGIC CRISIS", topicHeader: "Care of Clients with Multi-System Problem", topicOrder: 15, conceptText: "Multi-Organ Dysfunction Syndrome (MODS)", conceptOrder: 2, allocatedMinutes: 120 },

        // -- Airway, Breathing, Circulation (ABC) (topicOrder: 16) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Airway, Breathing, Circulation (ABC)", topicOrder: 16, conceptText: "Foreign Body Obstruction", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Airway, Breathing, Circulation (ABC)", topicOrder: 16, conceptText: "Inhalation Injury", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Airway, Breathing, Circulation (ABC)", topicOrder: 16, conceptText: "Thoracic Emergency", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Airway, Breathing, Circulation (ABC)", topicOrder: 16, conceptText: "Trauma", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Airway, Breathing, Circulation (ABC)", topicOrder: 16, conceptText: "Cardiac Arrest", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Airway, Breathing, Circulation (ABC)", topicOrder: 16, conceptText: "External Hemorrhage", conceptOrder: 5, allocatedMinutes: 120 },

        // -- Disability (topicOrder: 17) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Disability", topicOrder: 17, conceptText: "Head Injury", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Disability", topicOrder: 17, conceptText: "Stroke", conceptOrder: 1, allocatedMinutes: 120 },

        // -- Environmental Emergency (topicOrder: 18) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Environmental Emergency", topicOrder: 18, conceptText: "Heat-Related Emergencies", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Environmental Emergency", topicOrder: 18, conceptText: "Submersion Injuries", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Environmental Emergency", topicOrder: 18, conceptText: "Poisoning", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Environmental Emergency", topicOrder: 18, conceptText: "Drowning and Near Drowning", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Environmental Emergency", topicOrder: 18, conceptText: "Diving", conceptOrder: 4, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "Care of Clients with High Acuity and Emergency Situation: Medical Emergencies", topicHeader: "Environmental Emergency", topicOrder: 18, conceptText: "Lightning", conceptOrder: 5, allocatedMinutes: 120 },

        // -- OTHER NURSING CONCEPTS (topicOrder: 19) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: null, topicHeader: "OTHER NURSING CONCEPTS", topicOrder: 19, conceptText: "Concepts on Collaboration and Teamwork", conceptOrder: 0, allocatedMinutes: 120 },

        // -- Nurse Client Communication (topicOrder: 20) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Nurse Client Communication", topicOrder: 20, conceptText: "Components of Therapeutic Communication", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Nurse Client Communication", topicOrder: 20, conceptText: "Modes of Communication", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Nurse Client Communication", topicOrder: 20, conceptText: "Types of Communication", conceptOrder: 2, allocatedMinutes: 120 },

        // -- Documentation in Psychiatric Nursing Practice (topicOrder: 21) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Documentation in Psychiatric Nursing Practice", topicOrder: 21, conceptText: "Elements of Documentation", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Documentation in Psychiatric Nursing Practice", topicOrder: 21, conceptText: "Methods of Charting", conceptOrder: 1, allocatedMinutes: 120 },

        // -- Equipment Used for Acute, High Acuity and Emergency Cases (topicOrder: 22) --
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Equipment Used for Acute, High Acuity and Emergency Cases", topicOrder: 22, conceptText: "CPR Machine", conceptOrder: 0, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Equipment Used for Acute, High Acuity and Emergency Cases", topicOrder: 22, conceptText: "Ventilator", conceptOrder: 1, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Equipment Used for Acute, High Acuity and Emergency Cases", topicOrder: 22, conceptText: "Dialysis Machine", conceptOrder: 2, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Equipment Used for Acute, High Acuity and Emergency Cases", topicOrder: 22, conceptText: "ABG Analysis Machines", conceptOrder: 3, allocatedMinutes: 120 },
        { categoryName: "NURSING PRACTICE V: CARE OF CLIENTS WITH MALADAPTIVE PATTERNS OF BEHAVIOR (ACUTE & CHRONIC); CARE OF CLIENTS WITH LIFE-THREATENING CONDITION, ACUTELY ILL/MULTI-ORGAN PROBLEMS, HIGH ACUITY AND EMERGENCY SITUATION", categoryColorHex: "#351C75", categoryColorName: "Purple", categoryOrder: 4, groupLabel: "OTHER NURSING CONCEPTS", topicHeader: "Equipment Used for Acute, High Acuity and Emergency Cases", topicOrder: 22, conceptText: "TPN", conceptOrder: 4, allocatedMinutes: 120 },
    ]

    await prisma.pnleConcept.createMany({
        data: newCategory
    });

}

main()
    .catch((e) => {
        console.log(`Seeding Failed`),
        process.exit(1);
    })
    .finally( async() => {
        await prisma.$disconnect();
    })